

# Shapes î‚² î‚° î‚³ î‚± î‚¾ î‚¼ î‚¶ î‚´ î‚· î‚µ îƒ‡ îƒ† î‚¹ î‚¿ îƒ€ îƒ‚ îƒ îƒƒ î‚» î‚½ îƒŒ îƒ îƒˆ î‚¸ î‚º îƒ” îƒ’
#u'\uE0A2'

#$username\

#colors

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$fill\
$vcsh\
$hg_branch\
$docker_context\
$package\
$buf\
$cmake\
$cobol\
$container\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$sudo\
$cmd_duration\
$jobs\
$battery\
$status\
[\n â¯ ](fg:bright-blue)\
$shell"""

# A continuation prompt that displays two filled in arrows
#continuation_prompt = "î‚¼î‚¼"

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bg:bright-blue"
style_root = "bg:bright-blue"
format = "[ î‚¶](fg:bright-blue)[ïŒƒ $user]($style)[î‚´](fg:bright-blue bg:blue)"
# format = '[$user ]($style)'

[directory]
style = "bg:blue fg:bright-white"
format = "[ $path]($style)[î‚´](fg:blue)"
truncation_length = 4
truncation_symbol = "ï’ ï¼ "
read_only = "ï ½"

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ](bold red)" # used if previous command failed

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
"~" = "ï€• "
"/" = " ï¼ "

# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[git_branch]
symbol = "ï„“ ï˜"
style = "bg:bright-purple"
format = '[î‚¶](fg:bright-purple)[ $symbol $branch]($style)[ î‚¶](fg:purple bg:bright-purple)'

[git_status]
ahead = "î’ ${count}"
diverged = "î’ ${ahead_count} îŒ¿ ${behind_count}"
behind = "îŒ¿ ${count}"
up_to_date = "ï€Œ"
style = "bg:purple"
format = '[[($all_status$ahead_behind)](bg:purple)]($style)[î‚´ ](fg:purple)'

[cmd_duration]
style = "bg:blue"
format = '[î‚¶](fg:blue)[â± $duration ]($style)[î‚´ ](fg:blue)'

[fill]
symbol = " "
style = "black"

[battery]
full_symbol = "ï•¸ "
charging_symbol = "ï–ƒ "
discharging_symbol = "ï– "

[nodejs]
symbol = "îœ˜"
style = "bg:blue"
format = '[î‚¶](fg:blue)[ $symbol ]($style)[î‚´ ](fg:blue)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:black fg:bright-white"
format = '[î‚¶](fg:black)[ $time ]($style)[î‚´ ](fg:black)'

[aws]
symbol = "îŒ½  "
format = '[$symbol($profile)(\($region\))($duration)]($style)'

[conda]
style = "bg:#33658A"
format = '[$symbol$environment]($style)'
symbol = "ï„Œ "

[dart]
style = "bg:#33658A"
format = '[$symbol]($style)'
symbol = "î˜ "

[docker_context]
style = "bg:#33658A"
format = '[$symbol$context]($style)'
symbol = "ïŒˆ "

[elixir]
style = "bg:#33658A"
format = '[$symbol($version \(OTP $otp_version\))]($style)'
symbol = "î‰µ "

[elm]
style = "bg:#33658A"
format = '[$symbol]($style)'
symbol = "î˜¬ "

[golang]
style = "bg:#33658A"
format = '[$symbol]($style)'
symbol = "î˜§ "

[hg_branch]
style = "bg:#33658A"
format = '[$symbol$branch]($style)'
symbol = "ï˜ "

[java]
style = "bg:bright-red"
format = '[î‚¶](fg:bright-red)[$symbol $version]($style)[î‚´ ](fg:bright-red)'
symbol = "ï™µ "

[julia]
style = "bg:#33658A"
format = '[$symbol]($style)'
symbol = "î˜¤ "

[memory_usage]
style = "bg:#33658A"
format = '$symbol[$ram( | $swap)]($style)'
symbol = "ï¡š "

[nim]
style = "bg:#33658A"
format = '[$symbol]($style)'
symbol = "ïš¤ "

[nix_shell]
style = "bg:#33658A"
format = '[$symbol$state( \($name\))]($style)'
symbol = "ï‹œ "

[package]
style = "bg:#33658A"
format = '[$symbol$version]($style)'
symbol = "ï£– "

[cmake]
style = "bg:#33658A"
format = '[$symbol]($style)'

[cobol]
style = "bg:#33658A"
format = '[$symbol]($style)'

[crystal]
style = "bg:#33658A"
format = '[$symbol]($style)'

[deno]
style = "bg:#33658A"
format = '[$symbol]($style)'

[dotnet]
style = "bg:#33658A"
format = '[$symbol(ğŸ¯ $tfm)]($style)'

[erlang]
style = "bg:#33658A"
format = '[$symbol]($style)'

[gcloud]
style = "bg:#33658A"
format = '[$symbol$account(@$domain)(\($region\))]($style)'

[helm]
style = "bg:#33658A"
format = '[$symbol]($style)'

[jobs]
style = "bg:#33658A"
format = '[$symbol]($style)'

[kotlin]
style = "bg:#33658A"
format = '[$symbol]($style)'

[kubernetes]
style = "bg:#33658A"
format = '[$symbol$context( \($namespace\))]($style)'

[lua]
style = "bg:blue"
format = '[î‚¶](fg:blue)[$symbol $version]($style)[î‚´ ](fg:blue)'

[ocaml]
style = "bg:#33658A"
format = '[$symbol(\($switch_indicator$switch_name\))]($style)'

[openstack]
style = "bg:#33658A"
format = '[$symbol$cloud(\($project\))]($style)'

[perl]
style = "bg:#33658A"
format = '[$symbol]($style)'

[php]
style = "bg:#33658A"
format = '[$symbol]($style)'

[pulumi]
style = "bg:#33658A"
format = '[$symbol$stack]($style)'

[purescript]
style = "bg:#33658A"
format = '[$symbol]($style)'

[python]
symbol = "ï Ÿ"
style = "bg:blue fg:bright-yellow"
format = '[î‚¶](fg:blue)[${symbol} ${pyenv_prefix}(${version})(\($virtualenv\))]($style)[î‚´ ](fg:blue)'

[red]
style = "bg:#33658A"
format = '[$symbol]($style)'

[rlang]
symbol = "R ï·"
style = "bg:blue"
format = '[î‚¶](fg:blue)[$symbol $version]($style)[î‚´ ](fg:blue)'

[ruby]
style = "bg:#33658A"
format = '[$symbol]($style)'

[rust]
symbol = "î¨"
style = "bg:yellow"
format = '[î‚¶](fg:yellow)[$symbol $version]($style)[î‚´ ](fg:yellow)'

[scala]
style = "bg:#33658A"
format = '[$symbol]($style)'

[status]
style = "bg:#33658A"
format = '[$symbol]($style)'

[sudo]
style = "bg:#33658A"
format = '[as $symbol]'

[swift]
style = "bg:#33658A"
format = '[$symbol]($style)'

[terraform]
style = "bg:#33658A"
format = '[$symbol$workspace]($style)'

[vagrant]
style = "bg:#33658A"
format = '[$symbol]($style)'

[vlang]
style = "bg:#33658A"
format = '[$symbol]($style)'

[zig]
style = "bg:#33658A"
format = '[$symbol]($style)'


